### ISSUE TITLE
Authentication failed for user "plume"

### ISSUE THREAD

**Issue by Ilphrin** [Plume-org/Plume#157]
Hi,

After running `cargo run`, Plume create a 'plume' user and a database associated to it. But after setting the password, Plume says that it can't authenticate, as if the password was wrong (For test purpose, I tried with a simple password '**coucou**' without any special characters):

```
Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/plume`



Welcome in the Plume setup tool.
It will help you setup your new instance, by asking you a few questions.
Then you'll be able to enjoy Plume!

First let's check that you have all the required dependencies. Press Enter to start.

  ✔️ All native dependencies are present.

We are going to setup the database.

About to create a new PostgreSQL user named 'plume'

Enter password for new role: 
Enter it again: 
  ✔️ Done

About to create a new PostgreSQL database named 'plume'

  ✔️ Done

Running migrations…

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ConnectionError(BadConnection("FATAL:  password authentication failed for user \"plume\"\nFATAL:  password authentication failed for user \"plume\"\n"))', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'main' panicked at 'Couldn't init DB pool', libcore/option.rs:960:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

OS: Pop_OS! 18.04 (Ubuntu) 64 bits

Running with latest nightly rustc (with rustup) version

**Comment by Ilphrin** [comment]
Oh I see ^^ If I have some time I'll try to take a look at this (after installing a trying plume x) )

**Comment by jeroenpraat** [comment]
I have the same problem. 

I think it has to do with the fact that the system user 'plume' has not the permission to use Postgresql's createuser and createdb.

I also tried to create the user and database as the system user 'postgres', but when I run 'cargo run' again it still complains like this:

```
About to create a new PostgreSQL user named 'plume'

Enter password for new role: 
Enter it again: 
createuser: creation of new role failed: ERROR:  permission denied to create role
About to create a new PostgreSQL database named 'plume'

createdb: database creation failed: ERROR:  database "plume" already exists
```
So I'm stuck now at installing Plume. Please help?!

**Comment by BaptisteGelez** [comment]
@jeroenpraat A workaround would be to start Plume with this command:

```bash
DB_URL=postgres://USER:PASSWORD@localhost/plume cargo run
```

**Comment by jeroenpraat** [comment]
Thanks, I will try that tomorrow evening.

**Comment by jeroenpraat** [comment]
@BaptisteGelez Unfortunately this gives another issue:

```
$ DB_URL=postgres://plume:PASSWORD@localhost/plume cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s                                                     
     Running `target/debug/plume`
thread 'main' panicked at 'Error loading local instance infos: DatabaseError(__Unknown, "relation \"instances\" does not exist")', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

```
$ RUST_BACKTRACE=1 DB_URL=postgres://plume:PASSWORD@localhost/plume cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.75s                                                     
     Running `target/debug/plume`
thread 'main' panicked at 'Error loading local instance infos: DatabaseError(__Unknown, "relation \"instances\" does not exist")', libcore/result.rs:945:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:26
   9: <core::result::Result<T, E>>::expect
             at /checkout/src/libcore/result.rs:809
  10: plume_models::instance::Instance::get_local
             at plume-models/src/instance.rs:43
  11: plume::setup::check
             at src/setup.rs:31
  12: plume::main
             at src/main.rs:46
  13: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  14: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  15: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  16: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  17: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  18: main
  19: __libc_start_main
  20: _start
```

**Comment by jeroenpraat** [comment]
I think it has something to with peer authentication being the default for Postgresql on Debian. I can't find how to use a postgres:// url with peer auth.

**Comment by BaptisteGelez** [comment]
I think you need to run migrations to get you instance working. Try:

```
diesel migration run --database-url postgres://USER:PASSWORD@localhost/plume
```

**Comment by jeroenpraat** [comment]
@BaptisteGelez That was it! Ir is now asking for simple or complete setup :+1:

**Comment by BaptisteGelez** [comment]
The old setup script have been removed.
