### ISSUE TITLE
Broken Plume: database ?

### ISSUE THREAD

**Issue by maximesrd** [Plume-org/Plume#278]
Hello,
I tried to update plume but it doesn't work at all anymore:
```
thread 'main' panicked at 'Couldn't intialize database pool', libcore/option.rs:987:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: rust_begin_unwind
             at libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::option::expect_failed
             at libcore/option.rs:987
   9: <core::option::Option<T>>::expect
             at /checkout/src/libcore/option.rs:312
  10: plume::main
             at src/main.rs:59
  11: std::rt::lang_start::{{closure}}
             at /checkout/src/libstd/rt.rs:74
  12: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:106
  14: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  15: std::rt::lang_start
             at /checkout/src/libstd/rt.rs:74
  16: main
  17: __libc_start_main
  18: _start`

I tried to run migrations manually but:
`/home/maxime/.cargo/bin/diesel migration run --database-url postgres://plume:password@172.17.0.3:5432/plume
Invalid migration directory, the directory's name should be <timestamp>_<name_of_migration>, and it should only contain up.sql and down.sql. `
```

**EDIT: The problem came from use of DB_URL instead of DATABASE_URL**

Plume version (and/or commit): 0.20

**Comment by BaptisteGelez** [comment]
I think we should document these kind of changes when publishing a new release.
