### ISSUE TITLE
Cannot start plume ( 'main' panicked at 'called `Result::unwrap()` )

### ISSUE THREAD

**Issue by Dryusdan** [Plume-org/Plume#405]
Plume version (and/or commit): dfa89e2

Hello
After upgrade Plume to v0.2, I try to restart this with this command : 

```
/var/www/catlife.drycat.fr/.cargo/bin/plume
```
(I use this service file)

```
[Unit]
Description=plume

[Service]
Type=simple
User=plume
WorkingDirectory=/var/www/catlife.drycat.fr/Plume
ExecStart=/var/www/catlife.drycat.fr/.cargo/bin/plume
TimeoutSec=30
Restart=always

[Install]
WantedBy=multi-user.target
```

The command won't start et backtrace say this :
```
plume@Arcadia:~/Plume$ RUST_BACKTRACE=1 /var/www/catlife.drycat.fr/.cargo/bin/plume
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndexOpeningError', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
   9: plume::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

So, I have forgot something or not in compilation ?

**Comment by fdb-hiroshima** [comment]
You should be getting a nicer error message by now. Did you `cargo install ...` or just build?
There is a lock on the search index located in `$cwd/search_index/`, which did not get unlocked. This usually mean Plume got killed in a violent way (like power loss or SIGKILL), or it is still running and you are trying to start it twice.
If you are sure there is no other Plume running you can run `plm search unlock`, which will unlock the index

**Comment by Dryusdan** [comment]
I use 
```
cargo install --force && cargo install --path plume-cli --force
``` :)

I build it without stop it. Maybe is the reason :thinking:
Hum, okay, thank for this command.

I retry the update :)

**Comment by Dryusdan** [comment]
Hum, I launch a new compilation (with this script)
```
cd Plume
git pull origin master
FEATURES=postgres

cargo install -j 1 --force && cargo install -j 1 --path plume-cli --force --features $FEATURES
# Run the migrations
diesel migration run
```

But, when I try to start plume, and I receive this error : 
```
plume@Arcadia:~/Plume$ RUST_BACKTRACE=1 plume
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IndexOpeningError', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
   9: plume::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  13: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start
```

So, I try `plm search unlock`and I have the same error : 

```
plume@Arcadia:~/Plume$ RUST_BACKTRACE=1 plm search unlock
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:211
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:491
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:398
   6: rust_begin_unwind
             at src/libstd/panicking.rs:325
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:95
   8: core::result::unwrap_failed
   9: plm::search::run
  10: plm::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:59
             at src/libstd/panicking.rs:310
  13: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:102
  14: std::rt::lang_start_internal
             at src/libstd/panicking.rs:289
             at src/libstd/panic.rs:398
             at src/libstd/rt.rs:58
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by fdb-hiroshima** [comment]
Are you running Plume in the same directory as before?

**Comment by Dryusdan** [comment]
Yes :)

**Comment by fdb-hiroshima** [comment]
Does your previous version date from before 2018-12-02? If so, you have to build the search index, try to run `plm search init`. Else, could you run `ls -A search_index/`?

**Comment by Dryusdan** [comment]
Yes, I have an older version.
I run `plm search init`, so the search_index folder was created.
So I restart Plume and it work

Thank :)

**Comment by fdb-hiroshima** [comment]
May I close the issue?

**Comment by igalic** [comment]
would it be possible to catch these kind of panics in the future, and give a better error message instead?

**Comment by fdb-hiroshima** [comment]
I don't think we can catch theme, there is necessary data that is missing to run the server, and handling this case everywhere will add a lot of complexity. Giving a better error message would be possible, but there can be multiple reasons for index to fail opening: not being generated, being saved at the wrong place, being corrupted... and this one will definitely be rare, people following the installation guide won't get it, people with older installation are not numerous, so I think it's best to handle it by ourself

**Comment by BaptisteGelez** [comment]
I think we can close this issue?
