### ISSUE TITLE
Panick when I try to follow my Plume account from Pleroma

### ISSUE THREAD

**Issue by dfeyer** [Plume-org/Plume#415]
Plume: master

Backstrace:
```
plume_1     | thread '<unnamed>' panicked at 'instance::shared_inbox: user error: Request', src/libcore/result.rs:1009:5
plume_1     | stack backtrace:
plume_1     |    0:     0x5561c1c56323 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h0cd0554f80fdb8db
plume_1     |                                at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
plume_1     |    1:     0x5561c1c50328 - std::sys_common::backtrace::_print::h793e96c9ef310e7c
plume_1     |                                at src/libstd/sys_common/backtrace.rs:71
plume_1     |    2:     0x5561c1c54c12 - std::panicking::default_hook::{{closure}}::h841a24190f877711
plume_1     |                                at src/libstd/sys_common/backtrace.rs:59
plume_1     |                                at src/libstd/panicking.rs:211
plume_1     |    3:     0x5561c1c5497d - std::panicking::default_hook::hccb9ceccdd53c71e
plume_1     |                                at src/libstd/panicking.rs:227
plume_1     |    4:     0x5561c1c55320 - std::panicking::rust_panic_with_hook::he9362bdf637fc5d8
plume_1     |                                at src/libstd/panicking.rs:491
plume_1     |    5:     0x5561c1c54ea1 - std::panicking::continue_panic_fmt::h8c8ecd2074b327b3
plume_1     |                                at src/libstd/panicking.rs:398
plume_1     |    6:     0x5561c1c54d85 - rust_begin_unwind
plume_1     |                                at src/libstd/panicking.rs:325
plume_1     |    7:     0x5561c1c6d3bc - core::panicking::panic_fmt::hc84bf3901c1095d4
plume_1     |                                at src/libcore/panicking.rs:95
plume_1     |    8:     0x5561c1422389 - core::result::unwrap_failed::h91064b1ca0c520af
plume_1     |    9:     0x5561c137123f - plume::routes::instance::rocket_route_fn_shared_inbox::h7df73c7369c5c293
plume_1     |   10:     0x5561c1928fb9 - <F as rocket::handler::Handler>::handle::he0514bb9de3f8b13
plume_1     |   11:     0x5561c1939661 - rocket::rocket::Rocket::route_and_process::h129ad161cd87cc4b
plume_1     |   12:     0x5561c1937042 - <rocket::rocket::Rocket as hyper::server::Handler>::handle::h34b98d94f34d480d
plume_1     |   13:     0x5561c191dda1 - <hyper::server::Worker<H>>::handle_connection::hb7460aba0e169e58
plume_1     |   14:     0x5561c193f0de - hyper::server::listener::spawn_with::{{closure}}::h12b11c0298a71814
plume_1     |   15:     0x5561c193bf16 - std::sys_common::backtrace::__rust_begin_short_backtrace::hdf02cae49adcf693
plume_1     |   16:     0x5561c193bfa6 - std::panicking::try::do_call::h4ca5fab168c31c12
plume_1     |   17:     0x5561c1c66789 - __rust_maybe_catch_panic
plume_1     |                                at src/libpanic_unwind/lib.rs:102
plume_1     |   18:     0x5561c1908f97 - <F as alloc::boxed::FnBox<A>>::call_box::hd2fc54c51b56d262
plume_1     |   19:     0x5561c1c5a38d - std::sys::unix::thread::Thread::new::thread_start::h809dab03f76374f4
plume_1     |                                at /rustc/14997d56a550f4aa99fe737593cd2758227afc56/src/liballoc/boxed.rs:683
plume_1     |                                at src/libstd/sys_common/thread.rs:24
plume_1     |                                at src/libstd/sys/unix/thread.rs:90
plume_1     |   20:     0x7fbfd405c493 - start_thread
plume_1     |   21:     0x7fbfd3b87ace - __clone
plume_1     |   22:                0x0 - <unknown>
```

I try to follow https://blog.home-of-commons.org/@/dfeyer/followers

I can search for the account from Pleroma with success, has soon as I send the Follow Request, Plume is panicking

Mostly the same exception when i try to send a direct message from Pleroma to Plume.

Maybe it's related to my docker image (slim build)

**Comment by fdb-hiroshima** [comment]
I'm well able to reproduce on your instance, but not on others. It seems like for some reason, your Plume can't fetch users from remote instances, be them from Pleroma, Mastodon or even other Plume. Do you have some kind of restrictive firewall which might block https requests, or anything like that?

**Comment by dfeyer** [comment]
No firewall, but look my debian image does not have ca-certificates package installed :( that can make HTTPS communication impossible. I rebuild the image and test again.

**Comment by dfeyer** [comment]
OK my bad, with ca-certificates installed everything works 

https://github.com/Plume-org/Plume/issues/411#issuecomment-451780701 updated to add ca-certificates package in the final image.
