### ISSUE TITLE
Crash on start after upgrade

### ISSUE THREAD

**Issue by Dryusdan** [Plume-org/Plume#712]
Hi

I run an update from source code 0.3.0 to 0.4.0.

I run this command : 

```
cargo web deploy -p plume-front

# Update plm
cargo install --path plume-cli --force --features DATABASE
# Update plume
cargo install --path . --force --no-default-features --features DATABASE
```
and
```
plm migration run

Configuration read from /var/www/plume/www/.env
Running migration 20190620145757
Running migration 20190624101212
Running migration 20191210104935
```

After this step, I restart Plume and it crash.

So, I run plume without backtrace enable and when I going to landing page I have this log : 

```
plume@app-2:~/www$ RUST_BACKTRACE=full /var/www/plume/.cargo/bin/plume
Configuration read from /var/www/plume/www/.env
🔧 Configured for production.
    => address: 0.0.0.0
    => port: 7878
    => log: critical
    => workers: 4
    => secret key: provided
    => limits: forms = 128KiB, json* = 1MiB
    => keep-alive: 5s
    => tls: disabled
🚀 Rocket has launched from http://0.0.0.0:7878
thread '<unnamed>' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/cb2f34dc6d7e83d8bcfef79e0388d49f0c24aca7/src/libcore/slice/mod.rs:2539:10
stack backtrace:
   0:     0x55875ac93053 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h36afec69f8f732dc
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1:     0x55875ac8d80b - std::sys_common::backtrace::_print::h26887ef4b73ab4f4
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x55875ac90ab6 - std::panicking::default_hook::{{closure}}::hfdc01d49dd254ebc
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:197
   3:     0x55875ac90849 - std::panicking::default_hook::h358f870abe8abe7c
                               at src/libstd/panicking.rs:211
   4:     0x55875ac911bf - std::panicking::rust_panic_with_hook::h18482ef4f90a9f1c
                               at src/libstd/panicking.rs:474
   5:     0x55875ac90d41 - std::panicking::continue_panic_fmt::h5d07375313572b94
                               at src/libstd/panicking.rs:381
   6:     0x55875ac90c25 - rust_begin_unwind
                               at src/libstd/panicking.rs:308
   7:     0x55875acabc6c - core::panicking::panic_fmt::ha529b0a1690ccc0a
                               at src/libcore/panicking.rs:85
   8:     0x55875acabc24 - core::panicking::panic_bounds_check::h10dc177417d6cdb0
                               at src/libcore/panicking.rs:61
   9:     0x55875a1fa11b - plume::templates::partials::template_post_card::post_card::hc55478f991911b47
  10:     0x55875a137043 - plume::templates::template_base::base::h64543021f7da694c
  11:     0x55875a33caa9 - plume::templates::tags::template_index::index::h093c0a9c77ba66de
  12:     0x55875a2e740a - plume::routes::tags::rocket_route_fn_tag::h5eac2e1230d08ae1
  13:     0x55875a8c4849 - <F as rocket::handler::Handler>::handle::h3bf641ddc53cce2c
  14:     0x55875a8d4481 - rocket::rocket::Rocket::route_and_process::h9735b5e48458accc
  15:     0x55875a8d1edc - <rocket::rocket::Rocket as hyper::server::Handler>::handle::h91f94b0b3f3b4e45
  16:     0x55875a8c20df - hyper::server::Worker<H>::handle_connection::h5f38218bce76f46e
  17:     0x55875a8d031e - hyper::server::listener::spawn_with::{{closure}}::h69f0aba12525d02c
  18:     0x55875a8cd046 - std::sys_common::backtrace::__rust_begin_short_backtrace::h93935bfaffe923c9
  19:     0x55875a8c7476 - std::panicking::try::do_call::h4d65d457839ed98f
  20:     0x55875ac979a9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:87
  21:     0x55875a8a6017 - <F as alloc::boxed::FnBox<A>>::call_box::hc1c17098b1041f04
  22:     0x55875ac96ced - std::sys::unix::thread::Thread::new::thread_start::h9a484bddba837e0a
                               at /rustc/cb2f34dc6d7e83d8bcfef79e0388d49f0c24aca7/src/liballoc/boxed.rs:759
                               at src/libstd/sys_common/thread.rs:14
                               at src/libstd/sys/unix/thread.rs:80
  23:     0x7fa4aa2fc4a3 - start_thread
  24:     0x7fa4a9e27d0e - __clone
  25:                0x0 - <unknown>
```

- **Plume version:** 0.4.0
- **Operating system:** Debian 9.11
- **Web Browser:** Firefox 71

Regard

**Comment by fdb-hiroshima** [comment]
From the stracktrace, it looks line the issue come from [this line](https://github.com/Plume-org/Plume/blob/597778fd2f86139eb92ff54ea95229603d5215a9/templates/partials/post_card.rs.html#L22). This either mean the underlying sql request failed (but there is no reason for this request to fail, as previous ones to succeeded), or the post have 0 authors, which shouldn't happen.

**Comment by Dryusdan** [comment]
What is the SQL request ? I can test directly on PostgreSQL :)

**Comment by fdb-hiroshima** [comment]
I'm not sure exactly (sql request are generated by an ORM), but I'll try to give you a request that can tell you the offending post

**Comment by Djyp** [comment]
@Dryusdan Did you make it work ? I'm having the same problem now :/

**Comment by Djyp** [comment]
So :thinking: 

I figured with some messages ont the Riot chat that my users table didn't have a role field.

I found that the migration `2019-06-18-152700_moderator_role` wasn't properly applied (how ?)
So I ran it manually (I know, it's bad, the `plm migration` command didn't offer an option to run on rerun a specific migration)

```sql
ALTER TABLE users ADD COLUMN role INTEGER NOT NULL DEFAULT 2;
UPDATE users SET role = 0 WHERE is_admin = 't';
ALTER TABLE users DROP COLUMN is_admin;
```

and my instance is up and running again, and it's finally under v0.4.0

**Comment by Djyp** [comment]
Oh, but now my drafts are visible to everyone on the main page :open_mouth:

**Comment by Dryusdan** [comment]
@Djyp nope, actually my instance is on 0.3.0.
No upgrade. But your test look good.

Are you correct the problem with draft or not ?

**Comment by Dryusdan** [comment]
Ho wait, I read again your answer @Djyp and it good. With precompiled binary and your 3 psql requests and it work fine :dagger: 
Thank :)
