### ISSUE TITLE
/notifications internal server error (after deleting a blog and an article)

### ISSUE THREAD

**Issue by deckname** [Plume-org/Plume#759]
I have two accounts. On one account I posted an article in a blog, then deleted the blog and article and made a new blog and article. Before /notifications worked on this account, now it doesn't, when I click the bell it doesn't load and when I go to the URL directly as well. It gives a 500 internal server error. 

On a different account I can still view the /notifications url and receive notifications. 

Plume 0.4.0-alpha-4
- **Operating system:** Debian 9
- **Web Browser:** Firefox and Chromium

**Comment by Amolith** [comment]
I don't know if the root cause is the same but I'm experiencing the same issue and so is [another of my users](https://mastodon.social/@vasia/104210752525853977). I checked the logs for what happens directly after clicking the `Notifications` button and this is all that was output.

```
May 23 15:06:33 de1.nixnet.xyz plume[22621]: thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: Db(NotFound)', src/libcore/result.rs:997:5
```

I have it running with systemd so the command I ran to check logs was `journalctl -eu plume`. If there's another log location with more verbosity, I'm happy to provide output from there as well!

**Comment by elegaanz** [comment]
You can add `RUST_BACTRACE=1` to get a full backtrace next time, which may help.

**Comment by Amolith** [comment]
Sorry for taking so long to get back on this; I've been very busy the past little while. I added the env variable and this is the given backtrace when opening notifications.

```
thread '<unnamed>' panicked at 'instance::shared_inbox: user error: (Some(Object({"error": String("Gone")})), Inbox(InvalidObject(None)))', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: std::panicking::rust_panic_with_hook
   5: <unknown>
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <rocket::rocket::Rocket as hyper::server::Handler>::handle
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: __rust_maybe_catch_panic
  19: <unknown>
  20: <unknown>
  21: start_thread
  22: clone
```
