### ISSUE TITLE
Infinity loop: duplicate key value violates unique constraint "post_unique_slug"

### ISSUE THREAD

**Issue by manalejandro** [Plume-org/Plume#850]
Hi, sometimes my instance is doing infinity loops with this message in Docker containers:

```
plume             | thread 'pool-thread-#5' panicked at 'Article from remote user couldn't be saved: Db(DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"post_unique_slug\""))', plume-models/src/remote_fetch_actor.rs:76:30
plume-postgres    | ERROR:  duplicate key value violates unique constraint "post_unique_slug"
```

- **Plume version:** Plume 0.6.1-dev with official Dockerfile image
- **Operating system:** RaspiOS - Debian Buster with Docker
- **Web Browser:** none

**Comment by epsilon-phase** [comment]
Just out of curiosity, does this happen when you make a post with the same title as another post?

**Comment by KitaitiMakoto** [comment]
@manalejandro Thank you for reporting. Could you more logs around two lines you provided?
@epsilon-phase Thanks great pointing.

**Comment by manalejandro** [comment]
> @manalejandro Thank you for reporting. Could you paste more logs around two lines you provided?
> @epsilon-phase Thanks great pointing.

Yes it happens sometimes not everytime and i have no one article with then same title... attacks? 🤷
```
plume-postgres    | 2021-05-13 08:23:25.881 UTC [17772] ERROR:  duplicate key value violates unique constraint "post_unique_slug"
plume-postgres    | 2021-05-13 08:23:25.881 UTC [17772] DETAIL:  Key (blog_id, slug)=(3, roadmap) already exists.
plume-postgres    | 2021-05-13 08:23:25.881 UTC [17772] STATEMENT:  INSERT INTO "posts" ("blog_id", "slug", "title", "content", "published", "license", "creation_date", "ap_url", "subtitle", "source", "cover_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, DEFAULT)
plume             | thread 'pool-thread-#1' panicked at 'Article from remote user couldn't be saved: Db(DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"post_unique_slug\""))', plume-models/src/remote_fetch_actor.rs:76:30
plume-postgres    | 2021-05-13 08:23:31.435 UTC [17772] ERROR:  duplicate key value violates unique constraint "post_unique_slug"
plume-postgres    | 2021-05-13 08:23:31.435 UTC [17772] DETAIL:  Key (blog_id, slug)=(3, roadmap) already exists.
plume-postgres    | 2021-05-13 08:23:31.435 UTC [17772] STATEMENT:  INSERT INTO "posts" ("blog_id", "slug", "title", "content", "published", "license", "creation_date", "ap_url", "subtitle", "source", "cover_id") VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, DEFAULT)
plume             | thread 'pool-thread-#1' panicked at 'Article from remote user couldn't be saved: Db(DatabaseError(UniqueViolation, "duplicate key value violates unique constraint \"post_unique_slug\""))', plume-models/src/remote_fetch_actor.rs:76:30
```

**Comment by manalejandro** [comment]
I finally discovered that I was under attack until June 2021 and they filled my resources folder with 10Gb of photos, check the API, greetings.
